name = "pezines-api"
main = "src/worker.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

[vars]
GOV_URL = "https://eforms.eservices.cyprus.gov.cy/MCIT/MCIT/PetroleumPrices"

# Secrets (set via `wrangler secret put`):
#   ADMIN_API_KEY

[[kv_namespaces]]
binding = "KV"
id = "b759dff84b084bcfbc8c52030e12ea5f"
preview_id = "51ce2b95145f4e73a392fadc2b010d89"

[triggers]
crons = ["0 */6 * * *"]
